site_name: AGN Habitability Model
site_author: Jourdan Waas

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - user.color_mode.toggle

  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md

  - Getting Started:
      - Overview: getting-started.md
      - Installation: installation.md

  - Quickstart: 
      - Running the Models: running.md
      - Outputs: output.md

  - References: ref.md
  - Troubleshooting and Known Issues: issues.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true