site_name: AGN Habitability Model
site_author: Jourdan Waas

theme:
  name: material
  features:
    - user.color_mode.toggle
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
